# Generated by Django 5.2.6 on 2025-12-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='location',
        ),
    ]
