# Generated by Django 5.2.9 on 2026-01-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(help_text='Category of the complaint', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when complaint was created'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(help_text='Date when complaint was filed'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='name',
            field=models.CharField(help_text='Name of the complainant', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], help_text='Priority of the complaint', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='roomNo',
            field=models.CharField(help_text='Room number of the complainant', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='PENDING', help_text='Current status of the complaint', max_length=20),
        ),
    ]
